In [75]:
import polars as pl
import pandas as pd
import numpy as np

In [67]:
df = pl.read_csv('resources/age_children_income_1000.csv')
df

shape: (1_000, 3)
┌───────────┬────────────────────┬───────────────┐
│ age       ┆ number_of_children ┆ income        │
│ ---       ┆ ---                ┆ ---           │
│ f64       ┆ i64                ┆ f64           │
╞═══════════╪════════════════════╪═══════════════╡
│ 42.77242  ┆ 0                  ┆ 34396.537188  │
│ 29.56109  ┆ 0                  ┆ 183350.052521 │
│ 54.380735 ┆ 0                  ┆ 53689.856555  │
│ 42.551689 ┆ 0                  ┆ 109080.913926 │
│ 38.71308  ┆ 0                  ┆ 153612.343419 │
│ …         ┆ …                  ┆ …             │
│ 36.281055 ┆ 0                  ┆ 128647.922872 │
│ 18.472716 ┆ 0                  ┆ 67204.531673  │
│ 40.547748 ┆ 0                  ┆ 139432.757984 │
│ 24.79176  ┆ 1                  ┆ 137526.452334 │
│ 46.662848 ┆ 0                  ┆ 148449.261137 │
└───────────┴────────────────────┴───────────────┘

In [66]:
df.filter(df['age'] > 30).group_by('number_of_children', maintain_order=True).agg(pl.all().mean())

shape: (5, 3)
┌────────────────────┬───────────┬───────────────┐
│ number_of_children ┆ age       ┆ income        │
│ ---                ┆ ---       ┆ ---           │
│ i64                ┆ f64       ┆ f64           │
╞════════════════════╪═══════════╪═══════════════╡
│ 0                  ┆ 45.40922  ┆ 127031.101528 │
│ 1                  ┆ 37.456481 ┆ 133816.979041 │
│ 2                  ┆ 35.838748 ┆ 130462.897779 │
│ 3                  ┆ 38.464862 ┆ 193960.941571 │
│ 4                  ┆ 37.243996 ┆ 134556.79841  │
└────────────────────┴───────────┴───────────────┘

In [69]:
df.filter(pl.col('age') > 30)

shape: (733, 3)
┌───────────┬────────────────────┬───────────────┐
│ age       ┆ number_of_children ┆ income        │
│ ---       ┆ ---                ┆ ---           │
│ f64       ┆ i64                ┆ f64           │
╞═══════════╪════════════════════╪═══════════════╡
│ 42.77242  ┆ 0                  ┆ 34396.537188  │
│ 54.380735 ┆ 0                  ┆ 53689.856555  │
│ 42.551689 ┆ 0                  ┆ 109080.913926 │
│ 38.71308  ┆ 0                  ┆ 153612.343419 │
│ 54.643163 ┆ 0                  ┆ 114836.781583 │
│ …         ┆ …                  ┆ …             │
│ 40.265333 ┆ 0                  ┆ 109755.098519 │
│ 56.201693 ┆ 0                  ┆ 204514.993134 │
│ 36.281055 ┆ 0                  ┆ 128647.922872 │
│ 40.547748 ┆ 0                  ┆ 139432.757984 │
│ 46.662848 ┆ 0                  ┆ 148449.261137 │
└───────────┴────────────────────┴───────────────┘

In [82]:
some_array = [[1, 2, 3],
              [4, 5, 6],
              [np.nan, 8, 9],
              [10, 11, 12]]
df = pl.DataFrame(some_array,
				  schema=['a', 'b', 'c'],
                  orient='row')
print(df)

shape: (4, 3)
┌──────┬─────┬─────┐
│ a    ┆ b   ┆ c   │
│ ---  ┆ --- ┆ --- │
│ f64  ┆ i64 ┆ i64 │
╞══════╪═════╪═════╡
│ 1.0  ┆ 2   ┆ 3   │
│ 4.0  ┆ 5   ┆ 6   │
│ NaN  ┆ 8   ┆ 9   │
│ 10.0 ┆ 11  ┆ 12  │
└──────┴─────┴─────┘

In [91]:
df = pl.read_csv('resources/age_children_income_1000.csv')
df.sample(3)

shape: (3, 3)
┌───────────┬────────────────────┬───────────────┐
│ age       ┆ number_of_children ┆ income        │
│ ---       ┆ ---                ┆ ---           │
│ f64       ┆ i64                ┆ f64           │
╞═══════════╪════════════════════╪═══════════════╡
│ 43.020567 ┆ 0                  ┆ 124349.348024 │
│ 28.885583 ┆ 2                  ┆ 114196.885421 │
│ 28.073793 ┆ 1                  ┆ 50530.696548  │
└───────────┴────────────────────┴───────────────┘

In [96]:
df.select(pl.exclude('age'))

shape: (1_000, 2)
┌────────────────────┬───────────────┐
│ number_of_children ┆ income        │
│ ---                ┆ ---           │
│ i64                ┆ f64           │
╞════════════════════╪═══════════════╡
│ 0                  ┆ 34396.537188  │
│ 0                  ┆ 183350.052521 │
│ 0                  ┆ 53689.856555  │
│ 0                  ┆ 109080.913926 │
│ 0                  ┆ 153612.343419 │
│ …                  ┆ …             │
│ 0                  ┆ 128647.922872 │
│ 0                  ┆ 67204.531673  │
│ 0                  ┆ 139432.757984 │
│ 1                  ┆ 137526.452334 │
│ 0                  ┆ 148449.261137 │
└────────────────────┴───────────────┘

In [99]:
df.filter((pl.col('income').is_between(100_000, 200_000)) & (pl.col('age') > 30))

shape: (347, 3)
┌───────────┬────────────────────┬───────────────┐
│ age       ┆ number_of_children ┆ income        │
│ ---       ┆ ---                ┆ ---           │
│ f64       ┆ i64                ┆ f64           │
╞═══════════╪════════════════════╪═══════════════╡
│ 42.551689 ┆ 0                  ┆ 109080.913926 │
│ 38.71308  ┆ 0                  ┆ 153612.343419 │
│ 54.643163 ┆ 0                  ┆ 114836.781583 │
│ 33.676546 ┆ 0                  ┆ 193091.364233 │
│ 44.010106 ┆ 0                  ┆ 135829.562387 │
│ …         ┆ …                  ┆ …             │
│ 37.176344 ┆ 1                  ┆ 178957.529115 │
│ 40.265333 ┆ 0                  ┆ 109755.098519 │
│ 36.281055 ┆ 0                  ┆ 128647.922872 │
│ 40.547748 ┆ 0                  ┆ 139432.757984 │
│ 46.662848 ┆ 0                  ┆ 148449.261137 │
└───────────┴────────────────────┴───────────────┘

In [100]:
df.group_by('number_of_children', maintain_order=True).agg(pl.col('income').mean().alias('average_income'))

shape: (6, 2)
┌────────────────────┬────────────────┐
│ number_of_children ┆ average_income │
│ ---                ┆ ---            │
│ i64                ┆ f64            │
╞════════════════════╪════════════════╡
│ 0                  ┆ 126715.541703  │
│ 2                  ┆ 130142.466654  │
│ 1                  ┆ 132978.451169  │
│ 3                  ┆ 175810.993223  │
│ 5                  ┆ 99621.445364   │
│ 4                  ┆ 134556.79841   │
└────────────────────┴────────────────┘

In [161]:
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
    if len(a[0]) != len(b):
        return [-1]
    res = []
    for row in a:
        acc = sum([row[i] * b[i] for i in range(len(row))])
        res.append(acc)
    return res

In [162]:
print(matrix_dot_vector([[1, 2, 3], [2, 4, 5], [6, 8, 9]], [1, 2, 3]))

[14, 25, 49]